### ISSUE TITLE
Request for results

### ISSUE THREAD

**Issue by tarnh** [njh/early-trains#1]
Are there any results yet?

Can you trust self-reported data by Network Rail?

In Germany I wouldn't trust the official delay statistics. Train dispatchers tend to cover up any own wrongdoing.

**Comment by njh** [comment]
Hi,

Yes, I get the occasional email generated by this script about trains leaving my station early.
It is happening less frequently at the moment, then when I first wrote the script. Sometimes I report them and they respond saying that they will look into it.

My experience of looking at realtimetrains.co.uk while travelling on a train, is that the timings are very accurate. The reported data seems to be accurate to 1/4 of a minute.

To start with I wasn't sure if I could trust the data from Network Rail. But I think the data is all automated to the point where it would be difficult to fake some data and keep other data correct. 

At one point I did get a reply on twitter from a train driver, telling me to get up earlier!


nick.
